# Generated by Django 2.2.12 on 2021-01-07 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('author_first', models.CharField(max_length=20)),
                ('author_last', models.CharField(max_length=25)),
                ('date_published', models.DateField(default=datetime.datetime.now)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
    ]
