# Generated by Django 2.2.12 on 2021-01-07 01:59

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
    ]
